---
# Ruby version manager
rbenv:
  env: user
  version: v1.1.2
  default_ruby: 2.6.3
  rubies:
    - version: 2.6.3

rbenv_users: [vagrant]
rbenv_owner: 'vagrant'

# PostgreSQL
postgresql_version: 11
postgresql_encoding: 'UTF-8'
postgresql_databases:
  - name: test_database
    owner: test_user

postgresql_users:
  - name: test_user
    encrypted: yes
    pass: 123456

postgresql_user_privileges:
  - name: test_user
    db: test_database
    priv: "ALL"
    role_attr_flags: "SUPERUSER"

postgresql_listen_addresses:
  - '*'
