---
- hosts: local
  become: yes

  pre_tasks:
    - name: Autofollow to project on logon
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^cd /vagrant"
        line: "cd /vagrant"

    - name: Install a list of APT packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - libpq-dev

  roles:
    - role: rbenv
    - role: ntp
    - role: postgresql
